#!/bin/sh

cmake -B build . \
	-DCMAKE_TOOLCHAIN_FILE=ps2dev.cmake \
	-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
	-DCMAKE_BUILD_TYPE=Release \
	-DWITH_RSDK=ON \
	-DGAME_STATIC=ON \
	-DRETRO_REVISION=2 \
	-DRETRO_SUBSYSTEM=SDL2 \
	-DUSE_SDL_AUDIO=ON \
	-DPLATFORM=PlayStation2 \
	-DRETRO_MOD_LOADER=OFF
VERBOSE=1 cmake --build build
